param([string]$Version)

$content = @"
// <auto-generated/>
namespace ShrinkerGun
{
    internal static class BuildInfo
    {
        public const string Version = "$Version";
    }
}
"@

Set-Content -Path "$PSScriptRoot\BuildInfo.g.cs" -Value $content -Encoding UTF8
